# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('createupdatebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CreateUpdateBaseModel')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=170)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('branch_id', models.PositiveSmallIntegerField(default=0)),
                ('thumb_img', models.IntegerField(default=0)),
                ('num_comment', models.PositiveSmallIntegerField(default=0)),
                ('num_hit', models.BigIntegerField(default=0)),
                ('allow_comment', models.BinaryField(default=True)),
                ('is_public', models.BinaryField(default=True)),
            ],
            options={
                'db_table': 'article',
            },
            bases=('core.createupdatebasemodel',),
        ),
    ]
